export const FETCH_ADMINS = "FETCH_ADMINS";
export const SHOW_HIDE = "SHOW_HIDE";
export const FETCH_AGENTS = "FETCH_AGENTS";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_FOURNISSEUR = "FETCH_FOURNISSEUR";
export const FETCH_SERVICE = "FETCH_SERVICE";
export const FETCH_MATERIELS = "FETCH_MATERIELS";
export const FETCH_AGENCIES = "FETCH_AGENCIES";
export const FETCH_TOTAL_MATERIELS = "FETCH_TOTAL_MATERIELS";
export const FETCH_TOTAL_AVAILABLE_MATERIELS =
  "FETCH_TOTAL_AVAILABLE_MATERIELS";
export const FETCH_SERVICE_HIARCHY = "FETCH_SERVICE_HIARCHY";
export const FETCH_LIEUX = "FETCH_LIEUX";
export const FETCH_TABLE_COMPARAISON = "FETCH_TABLE_COMPARAISON";
export const FETCH_TABLE_EXIST = "FETCH_TABLE_EXIST";
export const FETCH_YEARS = "FETCH_YEARS";
